alter table public.profiles
  add column if not exists is_writer boolean not null default false;

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  slug text not null unique,
  topic text,
  tags text[] not null default '{}'::text[],
  excerpt text,
  cover_image_url text,
  content_raw text not null default '',
  blocks jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'published', 'rejected', 'archived')),
  admin_note text,
  submitted_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_blocks_array check (jsonb_typeof(blocks) = 'array')
);

alter table public.articles
  add column if not exists topic text,
  add column if not exists tags text[] not null default '{}'::text[],
  add column if not exists admin_note text,
  add column if not exists submitted_at timestamptz;

alter table public.articles
  drop constraint if exists articles_status_check;

alter table public.articles
  add constraint articles_status_check
  check (status in ('draft', 'submitted', 'published', 'rejected', 'archived'));

create index if not exists articles_author_id_idx on public.articles(author_id);
create index if not exists articles_status_published_at_idx on public.articles(status, published_at desc);
create index if not exists articles_category_id_idx on public.articles(category_id);
create index if not exists articles_topic_idx on public.articles(topic);
create index if not exists articles_tags_gin_idx on public.articles using gin(tags);

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row
execute function public.set_updated_at();

create or replace function public.admin_set_writer_access(target_user_id uuid, writer_enabled boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_role public.user_role;
begin
  select role into actor_role
  from public.profiles
  where id = auth.uid();

  if actor_role is distinct from 'admin' then
    raise exception 'Only admins can update writer access';
  end if;

  update public.profiles
  set is_writer = writer_enabled
  where id = target_user_id;
end;
$$;

grant execute on function public.admin_set_writer_access(uuid, boolean) to authenticated;

create or replace function public.can_author_articles()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and (
        role = 'admin'
        or role = 'instructor'
        or is_writer = true
      )
  );
$$;

grant execute on function public.can_author_articles() to authenticated;

alter table public.articles enable row level security;

drop policy if exists "Public can read published articles" on public.articles;
create policy "Public can read published articles"
on public.articles
for select
using (status = 'published');

drop policy if exists "Authors can manage visible articles" on public.articles;
create policy "Authors can manage visible articles"
on public.articles
for select
to authenticated
using (
  status = 'published'
  or author_id = auth.uid()
  or exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

drop policy if exists "Authors can create articles" on public.articles;
create policy "Authors can create articles"
on public.articles
for insert
to authenticated
with check (
  public.can_author_articles()
  and (
    author_id = auth.uid()
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  )
);

drop policy if exists "Authors can update their articles" on public.articles;
create policy "Authors can update their articles"
on public.articles
for update
to authenticated
using (
  author_id = auth.uid()
  or exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
)
with check (
  public.can_author_articles()
  and (
    author_id = auth.uid()
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  )
);

drop policy if exists "Authors can delete their articles" on public.articles;
create policy "Authors can delete their articles"
on public.articles
for delete
to authenticated
using (
  (status = 'draft' and author_id = auth.uid())
  or exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);
