import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { workflowActions, validateReviewInput, scheduleFromJakarta, hasPublicationText } from "../lib/article-workflow.mjs";

test("Review reasons, permissions, publication text and Jakarta schedule validation", () => {
  assert.deepEqual(workflowActions(false,"submitted"),[]);
  assert.equal(workflowActions(true,"published")[0].status,"archived");
  assert.equal(workflowActions(false,"rejected")[0].status,"draft");
  assert.equal(workflowActions(true,"draft")[0].status,"submitted");
  assert.throws(() => validateReviewInput({ status:"rejected", note:" " }));
  assert.throws(() => validateReviewInput({ status:"published", note:"x".repeat(4001) }));
  assert.equal(validateReviewInput({ status:"rejected", note:" Perbaiki sumber " }).note,"Perbaiki sumber");
  assert.equal(hasPublicationText({ type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"  "}]}] }),false);
  assert.equal(hasPublicationText({ type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"Isi"}]}] }),true);
  const now = new Date("2026-10-06T06:00:00Z");
  assert.equal(scheduleFromJakarta("2026-10-06T16:00",now),"2026-10-06T09:00:00.000Z");
  assert.throws(() => scheduleFromJakarta("2026-10-06T13:00",now));
  assert.equal(scheduleFromJakarta("2026-10-07T00:30",now),"2026-10-06T17:30:00.000Z");
  for (const value of ["2026-10-06T08:00","2026-02-30T12:00","2026-10-07T25:00","2027-10-07T12:00","2028-10-06T12:00","not a date"]) assert.throws(() => scheduleFromJakarta(value,now));
});

test("Workflow SQL protects revisions, notes, CAS and automatic publication", async () => {
  const db = new PGlite();
  const writer="00000000-0000-0000-0000-000000000001", other="00000000-0000-0000-0000-000000000002", admin="00000000-0000-0000-0000-000000000003", student="00000000-0000-0000-0000-000000000004";
  const sql = (file) => readFile(new URL(`../../supabase/${file}`,import.meta.url),"utf8");
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create type public.user_role as enum ('student','instructor','admin');
      create table public.profiles(id uuid primary key,role public.user_role default 'student',is_writer boolean default false);
      create table public.categories(id bigint primary key);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      create function auth.role() returns text language sql stable as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;
      create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at:=now(); return new; end $$;
      grant usage on schema public,auth to anon,authenticated,service_role;
      grant select on public.profiles to anon,authenticated;
      insert into public.profiles values ('${writer}','student',true),('${other}','instructor',false),('${admin}','admin',false),('${student}','student',false);
    `);
    await db.exec(await sql("articles_patch.sql"));
    await db.exec(await sql("account_center_patch.sql"));
    await db.exec(`insert into public.articles(author_id,title,slug,content_raw,blocks) values ('${writer}','Legacy','legacy','Old source','[{"type":"p","children":[{"text":"Old source"}]}]'); grant select on public.articles to anon;`);
    await db.exec(await sql("editorial_foundation_patch.sql"));
    const migration = await sql("editorial_workflow_patch.sql");
    await db.exec(migration); await db.exec(migration);
    async function login(id,role="authenticated") { await db.exec("reset role"); await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[id,role]); await db.exec(`set role ${role}`); }
    const row = async (id=1) => (await db.query("select * from public.articles where id=$1",[id])).rows[0];
    const revisions = async () => (await db.query("select * from public.article_revisions where article_id=1 order by revision_number")).rows;
    const deny = (statement) => assert.rejects(db.exec(statement));
    await login(writer);
    await db.exec(`update public.articles set title='Edited',content_json='{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Article text"}]}]}' where id=1 and version=1`);
    assert.equal((await revisions())[0].reason,"baseline");
    assert.equal((await revisions())[0].content_raw,"Old source");
    const firstSnapshot = (await db.query("select public.snapshot_editorial_article(1,2) as id")).rows[0].id;
    assert.equal((await db.query("select public.snapshot_editorial_article(1,2) as id")).rows[0].id,firstSnapshot);
    assert.equal((await row()).version,2);
    await deny("select public.snapshot_editorial_article(1,1)");
    await deny("delete from public.article_revisions");
    await deny("update public.article_revisions set reason='Forged'");
    await deny("select public.write_editorial_revision((select a from public.articles a where id=1),'manual')");
    await deny("update public.articles set scheduled_at=now()+interval '1 hour' where id=1");
    await db.exec("select public.transition_editorial_article(1,2,'submitted')");
    assert.equal((await revisions()).at(-1).reason,"submitted");
    await deny("select public.schedule_editorial_article(1,3,now()+interval '1 hour')");
    await deny("select public.publish_due_editorial_articles()");
    await login(other);
    assert.equal((await revisions()).length,0);
    await deny("select public.snapshot_editorial_article(1,3)");
    await login(student);
    assert.equal((await revisions()).length,0);
    await deny("select public.snapshot_editorial_article(1,3)");
    await login(admin);
    await deny("select public.transition_editorial_article(1,3,'rejected','')");
    await db.exec("select public.transition_editorial_article(1,3,'rejected','Perbaiki sumber')");
    assert.equal((await revisions()).at(-1).metadata_json.admin_note,"Perbaiki sumber");
    await login(writer);
    await db.exec("select public.transition_editorial_article(1,4,'draft')");
    await db.exec("select public.transition_editorial_article(1,5,'submitted')");
    await login(admin);
    assert.equal((await db.query("select public.editorial_scheduler_ready() as ready")).rows[0].ready,false);
    await deny("select public.schedule_editorial_article(1,6,now()+interval '1 hour')");
    // Model an installed database Cron job; tests never access Supabase Cron.
    await db.exec("reset role; create schema cron; create table cron.job(jobname text,active boolean,database text,username text,command text); insert into cron.job values ('editorial-publish-due',true,current_database(),current_user,'select public.publish_due_editorial_articles();');");
    await login(admin);
    assert.equal((await db.query("select public.editorial_scheduler_ready() as ready")).rows[0].ready,true);
    await deny("select public.schedule_editorial_article(1,6,now()-interval '1 hour')");
    await db.exec("select public.schedule_editorial_article(1,6,now()+interval '1 hour')");
    assert.equal((await row()).version,7);
    assert.equal((await revisions()).at(-1).reason,"scheduled");
    await deny("select public.schedule_editorial_article(1,6,null)");
    await db.exec("select public.schedule_editorial_article(1,7,null)");
    assert.equal((await row()).scheduled_at,null);
    await db.exec("select public.schedule_editorial_article(1,8,now()+interval '1 hour')");
    await login("","service_role");
    assert.equal((await db.query("select public.publish_due_editorial_articles() as count")).rows[0].count,0);
    await db.exec("reset role; update public.articles set scheduled_at=now()-interval '1 minute' where id=1;");
    await login("","service_role");
    assert.equal((await db.query("select public.publish_due_editorial_articles() as count")).rows[0].count,1);
    assert.equal((await db.query("select auth.role() as role")).rows[0].role,"service_role");
    assert.equal((await db.query("select public.publish_due_editorial_articles() as count")).rows[0].count,0);
    await login(admin);
    let article=await row();
    assert.equal(article.status,"published"); assert.ok(article.published_at); assert.equal(article.scheduled_at,null);
    assert.equal((await revisions()).at(-1).reason,"published");
    await db.exec("update public.articles set admin_note='Catatan tersimpan' where id=1");
    assert.equal((await revisions()).at(-1).reason,"review_note");
    article=await row();
    await db.exec(`select public.transition_editorial_article(1,${article.version},'archived')`);
    article=await row();
    await db.exec(`select public.transition_editorial_article(1,${article.version},'draft')`);
    article=await row();
    assert.equal(article.published_at,null);
    await db.exec("reset role; update public.article_revisions set created_at=now()-interval '6 minutes' where article_id=1");
    await login(writer);
    await db.exec("update public.articles set excerpt='Perubahan setelah lima menit' where id=1");
    assert.equal((await revisions()).at(-1).reason,"autosave");
    article=await row();
    await login("","anon");
    assert.equal((await db.query("select id from public.articles where id=1")).rows.length,0);
    await deny("select * from public.article_revisions");
    await deny("select public.publish_due_editorial_articles()");
    // Worker also handles missing content without repeatedly retrying a broken article.
    await login(admin);
    await db.exec(`select public.transition_editorial_article(1,${article.version},'submitted')`);
    article=await row();
    await db.exec(`select public.schedule_editorial_article(1,${article.version},now()+interval '1 hour')`);
    await login("","service_role");
    await db.exec("reset role; update public.articles set scheduled_at=now()-interval '1 minute',content_json=null where id=1");
    await db.exec("select public.publish_due_editorial_articles()");
    assert.equal((await db.query("select auth.role() as role")).rows[0].role,"service_role");
    await login(admin);
    assert.equal((await row()).status,"submitted"); assert.match((await row()).publication_error,/gagal/);
    assert.equal((await revisions()).at(-1).reason,"publication_failed");
    await deny("select public.publish_due_editorial_articles()");
    await db.exec("reset role; select public.publish_due_editorial_articles()");
    assert.equal((await db.query("select auth.role() as role")).rows[0].role,"authenticated");
    // Phase 6 restoration is atomic, versioned, restricted, and immutable.
    const polish = await sql("editorial_polish_patch.sql");
    await db.exec(polish); await db.exec(polish);
    await login(admin);
    article = await row();
    await deny(`select public.restore_editorial_revision(1,${article.version},${firstSnapshot})`);
    await db.exec(`select public.transition_editorial_article(1,${article.version},'draft')`);
    article = await row();
    const baseline = (await revisions())[0];
    const versionBeforeRestore = article.version;
    const noteBeforeRestore = article.admin_note;
    await login(other);
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore},${baseline.id})`);
    await login(student);
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore},${baseline.id})`);
    await login("","anon");
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore},${baseline.id})`);
    await login(writer);
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore - 1},${baseline.id})`);
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore},9999999)`);
    assert.equal((await row()).version,versionBeforeRestore);
    await db.exec(`select public.restore_editorial_revision(1,${versionBeforeRestore},${baseline.id})`);
    article = await row();
    assert.equal(article.version,versionBeforeRestore+1);
    assert.equal(article.title,"Legacy");
    assert.equal(article.content_raw,"Old source");
    assert.equal(article.content_json,null);
    assert.equal(article.status,"draft");
    assert.equal(article.admin_note,noteBeforeRestore);
    assert.equal(article.author_id,writer);
    assert.equal(article.slug,"legacy");
    assert.ok((await revisions()).some(item=>item.reason === "before_restore" && item.article_version === versionBeforeRestore));
    assert.equal((await revisions()).at(-1).reason,"restored");
    await deny(`select public.restore_editorial_revision(1,${versionBeforeRestore},${firstSnapshot})`);
    await db.exec(`select public.restore_editorial_revision(1,${article.version},${firstSnapshot})`);
    assert.equal((await row()).content_json.content[0].content[0].text,"Article text");
    await login(other);
    await db.exec(`insert into public.articles(author_id,title,slug) values ('${other}','Other draft','other-draft')`);
    const foreignRevision = (await db.query("select id from public.article_revisions where article_id=2")).rows[0].id;
    await login(admin);
    article = await row();
    const countBeforeFailure = (await revisions()).length;
    await deny(`select public.restore_editorial_revision(1,${article.version},${foreignRevision})`);
    assert.equal((await revisions()).length,countBeforeFailure);
    await db.exec(`select public.transition_editorial_article(1,${article.version},'submitted')`);
    article = await row();
    await db.exec(`select public.transition_editorial_article(1,${article.version},'published')`);
    article = await row();
    await deny(`select public.restore_editorial_revision(1,${article.version},${firstSnapshot})`);
  } finally { await db.close(); }
});
